<h1>Project 2 United Kingdom Accidents

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import f_oneway

In [2]:
ukacc = pd.read_csv('dataset//uk_road_accident.csv')

In [3]:
ukacc

Index Accident_Severity Accident Date   Latitude  \
0       200701BS64157           Serious      5/6/2019  51.506187   
1       200701BS65737           Serious      2/7/2019  51.495029   
2       200701BS66127           Serious    26-08-2019  51.517715   
3       200701BS66128           Serious    16-08-2019  51.495478   
4       200701BS66837            Slight      3/9/2019  51.488576   
...               ...               ...           ...        ...   
660674  201091NM01760            Slight    18-02-2022  57.374005   
660675  201091NM01881            Slight    21-02-2022  57.232273   
660676  201091NM01935            Slight    23-02-2022  57.585044   
660677  201091NM01964           Serious    23-02-2022  57.214898   
660678  201091NM02142           Serious    28-02-2022  57.575210   

                   Light_Conditions           District Area  Longitude  \
0             Darkness - lights lit  Kensington and Chelsea  -0.209082   
1                          Daylight  Kensington and Chelsea  -0.173647   
2       Darkness - lighting unknown  Kensington and Chelsea  -0.210215   
3                          Daylight  Kensington and Chelsea  -0.202731   
4             Darkness - lights lit  Kensington and Chelsea  -0.192487   
...                             ...                     ...        ...   
660674                     Daylight                Highland  -3.467828   
660675       Darkness - no lighting                Highland  -3.809281   
660676                     Daylight                Highland  -3.862727   
660677       Darkness - no lighting                Highland  -3.823997   
660678                     Daylight                Highland  -3.895673   

        Number_of_Casualties  Number_of_Vehicles Road_Surface_Conditions  \
0                          1                   2                     Dry   
1                          1                   2             Wet or damp   
2                          1                   3                     Dry   
3                          1                   4                     Dry   
4                          1                   2                     Dry   
...                      ...                 ...                     ...   
660674                     2                   1                     Dry   
660675                     1                   1            Frost or ice   
660676                     1                   3            Frost or ice   
660677                     1                   2             Wet or damp   
660678                     1                   1             Wet or damp   

                 Road_Type Urban_or_Rural_Area     Weather_Conditions  \
0       Single carriageway               Urban     Fine no high winds   
1       Single carriageway               Urban  Raining no high winds   
2                      NaN               Urban                    NaN   
3       Single carriageway               Urban     Fine no high winds   
4                      NaN               Urban                    NaN   
...                    ...                 ...                    ...   
660674  Single carriageway               Rural     Fine no high winds   
660675  Single carriageway               Rural     Fine no high winds   
660676  Single carriageway               Rural     Fine no high winds   
660677  Single carriageway               Rural     Fine no high winds   
660678    Dual carriageway               Rural  Snowing no high winds   

                                Vehicle_Type  
0                                        Car  
1                                        Car  
2                      Taxi/Private hire car  
3       Bus or coach (17 or more pass seats)  
4                              Other vehicle  
...                                      ...  
660674                                   Car  
660675                                   Car  
660676                                   Car  
660677                 Motorcycle over 500cc  
660

In [4]:
ukacc.describe().T

count       mean       std        min        25%  \
Latitude              660654.0  52.553866  1.406922  49.914430  51.490690   
Longitude             660653.0  -1.431210  1.383330  -7.516225  -2.332291   
Number_of_Casualties  660679.0   1.357040  0.824847   1.000000   1.000000   
Number_of_Vehicles    660679.0   1.831255  0.715269   1.000000   1.000000   

                            50%        75%        max  
Latitude              52.315641  53.453452  60.757544  
Longitude             -1.411667  -0.232869   1.762010  
Number_of_Casualties   1.000000   1.000000  68.000000  
Number_of_Vehicles     2.000000   2.000000  32.000000

In [5]:
ukacc['Accident Date'] = pd.to_datetime(ukacc['Accident Date'], dayfirst=True, errors = 'coerce')

In [6]:
ukacc.dtypes

Index                              object
Accident_Severity                  object
Accident Date              datetime64[ns]
Latitude                          float64
Light_Conditions                   object
District Area                      object
Longitude                         float64
Number_of_Casualties                int64
Number_of_Vehicles                  int64
Road_Surface_Conditions            object
Road_Type                          object
Urban_or_Rural_Area                object
Weather_Conditions                 object
Vehicle_Type                       object
dtype: object

In [7]:
ukacc.isnull().sum()

Index                           0
Accident_Severity               0
Accident Date              395672
Latitude                       25
Light_Conditions                0
District Area                   0
Longitude                      26
Number_of_Casualties            0
Number_of_Vehicles              0
Road_Surface_Conditions       726
Road_Type                    4520
Urban_or_Rural_Area            15
Weather_Conditions          14128
Vehicle_Type                    0
dtype: int64

In [8]:
ukacc['Latitude'] = ukacc ['Latitude'].fillna(ukacc['Latitude'].mode()[0])

In [9]:
ukacc['Longitude'] = ukacc ['Longitude'].fillna(ukacc['Longitude'].mode()[0])
ukacc['Road_Surface_Conditions'] = ukacc ['Road_Surface_Conditions'].fillna('unaccounted')
ukacc['Road_Type'] = ukacc ['Road_Type'].fillna('unaccounted')
ukacc['Weather_Conditions'] = ukacc ['Weather_Conditions'].fillna(ukacc['Weather_Conditions'].mode()[0])
ukacc['Urban_or_Rural_Area'] = ukacc ['Urban_or_Rural_Area'].fillna(ukacc['Urban_or_Rural_Area'].mode()[0])

In [10]:
ukacc.isnull().sum()

Index                           0
Accident_Severity               0
Accident Date              395672
Latitude                        0
Light_Conditions                0
District Area                   0
Longitude                       0
Number_of_Casualties            0
Number_of_Vehicles              0
Road_Surface_Conditions         0
Road_Type                       0
Urban_or_Rural_Area             0
Weather_Conditions              0
Vehicle_Type                    0
dtype: int64

In [11]:
ukacc['Accident Date'] = ukacc ['Accident Date'].fillna(ukacc['Accident Date'].mode()[0])
ukacc['Year'] = ukacc['Accident Date'].dt.year
ukacc['Month'] = ukacc['Accident Date'].dt.month
ukacc['Day'] = ukacc['Accident Date'].dt.day
ukacc['DayOfWeek'] = ukacc['Accident Date'].dt.dayofweek

In [12]:
ukacc.isnull().sum()

Index                      0
Accident_Severity          0
Accident Date              0
Latitude                   0
Light_Conditions           0
District Area              0
Longitude                  0
Number_of_Casualties       0
Number_of_Vehicles         0
Road_Surface_Conditions    0
Road_Type                  0
Urban_or_Rural_Area        0
Weather_Conditions         0
Vehicle_Type               0
Year                       0
Month                      0
Day                        0
DayOfWeek                  0
dtype: int64

<h1>Exploratory Data Analytics

<h2> 1.how many traffic accident were serious

In [13]:
ukacc[ukacc ['Accident_Severity'] == 'Serious']

Index Accident_Severity Accident Date   Latitude  \
0       200701BS64157           Serious    2019-06-05  51.506187   
1       200701BS65737           Serious    2019-07-02  51.495029   
2       200701BS66127           Serious    2021-02-11  51.517715   
3       200701BS66128           Serious    2021-02-11  51.495478   
5       200701BS67159           Serious    2021-02-11  51.497750   
...               ...               ...           ...        ...   
660629  201091NL00686           Serious    2022-02-11  57.687933   
660645  201091NL05842           Serious    2021-02-11  60.162660   
660672  201091NM01085           Serious    2021-02-11  57.170725   
660677  201091NM01964           Serious    2021-02-11  57.214898   
660678  201091NM02142           Serious    2021-02-11  57.575210   

                   Light_Conditions           District Area  Longitude  \
0             Darkness - lights lit  Kensington and Chelsea  -0.209082   
1                          Daylight  Kensington and Chelsea  -0.173647   
2       Darkness - lighting unknown  Kensington and Chelsea  -0.210215   
3                          Daylight  Kensington and Chelsea  -0.202731   
5                          Daylight  Kensington and Chelsea  -0.192556   
...                             ...                     ...        ...   
660629                     Daylight        Shetland Islands  -4.176860   
660645                     Daylight        Shetland Islands  -1.165232   
660672                     Daylight                Highland  -3.852421   
660677       Darkness - no lighting                Highland  -3.823997   
660678                     Daylight                Highland  -3.895673   

        Number_of_Casualties  Number_of_Vehicles Road_Surface_Conditions  \
0                          1                   2                     Dry   
1                          1                   2             Wet or damp   
2                          1                   3                     Dry   
3                          1                   4                     Dry   
5                          2                   3                     Dry   
...                      ...                 ...                     ...   
660629                     1                   2                     Dry   
660645                     1                   1                     Dry   
660672                     1                   2                    Snow   
660677                     1                   2             Wet or damp   
660678                     1                   1             Wet or damp   

                 Road_Type Urban_or_Rural_Area     Weather_Conditions  \
0       Single carriageway               Urban     Fine no high winds   
1       Single carriageway               Urban  Raining no high winds   
2              unaccounted               Urban     Fine no high winds   
3       Single carriageway               Urban     Fine no high winds   
5       Single carriageway               Urban     Fine no high winds   
...                    ...                 ...                    ...   
660629  Single carriageway               Rural      Fine + high winds   
660645  Single carriageway               Rural      Fine + high winds   
660672  Single carriageway               Rural     Fine no high winds   
660677  Single carriageway               Rural     Fine no high winds   
660678    Dual carriageway               Rural  Snowing no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
0                                        Car  2019      6    5          2  
1                                        Car  2019      7    2          1  
2                      Taxi/Private hire car  2021      2   11          3  
3       Bus or coach (17 or more pass seats)  2021      2   11          3  
5                                        Car  2021      2   11          3  
...                                      ...   ...    ...  ...  

<h2>Insight#1

<h3>There's 88217 that's serious

<h2>2.How many that are in Slight conditions on accidents severity

In [14]:
ukacc[ukacc ['Accident_Severity'] == 'Slight']

Index Accident_Severity Accident Date   Latitude  \
4       200701BS66837            Slight    2019-09-03  51.488576   
8       200701BS67515            Slight    2021-02-11  51.493319   
9       200701BS67543            Slight    2021-02-11  51.484539   
13      200701BS67853            Slight    2019-11-08  51.508999   
14      200701BS67859            Slight    2019-11-01  51.485125   
...               ...               ...           ...        ...   
660671  201091NM01053            Slight    2021-02-11  57.572162   
660673  201091NM01190            Slight    2022-02-02  57.585152   
660674  201091NM01760            Slight    2021-02-11  57.374005   
660675  201091NM01881            Slight    2021-02-11  57.232273   
660676  201091NM01935            Slight    2021-02-11  57.585044   

              Light_Conditions           District Area  Longitude  \
4        Darkness - lights lit  Kensington and Chelsea  -0.192487   
8        Darkness - lights lit  Kensington and Chelsea  -0.173572   
9                     Daylight  Kensington and Chelsea  -0.175651   
13       Darkness - lights lit  Kensington and Chelsea  -0.210701   
14       Darkness - lights lit  Kensington and Chelsea  -0.167129   
...                        ...                     ...        ...   
660671                Daylight                Highland  -3.930799   
660673                Daylight                Highland  -3.748312   
660674                Daylight                Highland  -3.467828   
660675  Darkness - no lighting                Highland  -3.809281   
660676                Daylight                Highland  -3.862727   

        Number_of_Casualties  Number_of_Vehicles Road_Surface_Conditions  \
4                          1                   2                     Dry   
8                          1                   2                     Dry   
9                          1                   2                     Dry   
13                         3                   2             Wet or damp   
14                         1                   1                     Dry   
...                      ...                 ...                     ...   
660671                     1                   1            Frost or ice   
660673                     2                   2             Wet or damp   
660674                     2                   1                     Dry   
660675                     1                   1            Frost or ice   
660676                     1                   3            Frost or ice   

                 Road_Type Urban_or_Rural_Area  Weather_Conditions  \
4              unaccounted               Urban  Fine no high winds   
8       Single carriageway               Urban  Fine no high winds   
9       Single carriageway               Urban  Fine no high winds   
13      Single carriageway               Urban               Other   
14          One way street               Urban  Fine no high winds   
...                    ...                 ...                 ...   
660671  Single carriageway               Rural               Other   
660673  Single carriageway               Rural  Fine no high winds   
660674  Single carriageway               Rural  Fine no high winds   
660675  Single carriageway               Rural  Fine no high winds   
660676  Single carriageway               Rural  Fine no high winds   

                                 Vehicle_Type  Year  Month  Day  DayOfWeek  
4                               Other vehicle  2019      9    3          1  
8                                         Car  2021      2   11          3  
9       Motorcycle over 125cc and up to 500cc  2021      2   11          3  
13                                        Car  2019     11    8          4  
14                                        Car  2019     11    1          4  
...                                       ...   ...    ...  ...        ...  
660671    Van / Goods 3.5 tonnes mgw or under  2021      2   11          3  


<h2>Insight#2
<h3>theres 53801 that are in slight conditons

<h2>3.how many that are in broad daylight that got into an accident

In [15]:
ukacc[ukacc ['Light_Conditions'] == 'Daylight']

Index Accident_Severity Accident Date   Latitude  \
1       200701BS65737           Serious    2019-07-02  51.495029   
3       200701BS66128           Serious    2021-02-11  51.495478   
5       200701BS67159           Serious    2021-02-11  51.497750   
6       200701BS67207           Serious    2019-09-05  51.501405   
9       200701BS67543            Slight    2021-02-11  51.484539   
...               ...               ...           ...        ...   
660672  201091NM01085           Serious    2021-02-11  57.170725   
660673  201091NM01190            Slight    2022-02-02  57.585152   
660674  201091NM01760            Slight    2021-02-11  57.374005   
660676  201091NM01935            Slight    2021-02-11  57.585044   
660678  201091NM02142           Serious    2021-02-11  57.575210   

       Light_Conditions           District Area  Longitude  \
1              Daylight  Kensington and Chelsea  -0.173647   
3              Daylight  Kensington and Chelsea  -0.202731   
5              Daylight  Kensington and Chelsea  -0.192556   
6              Daylight  Kensington and Chelsea  -0.161577   
9              Daylight  Kensington and Chelsea  -0.175651   
...                 ...                     ...        ...   
660672         Daylight                Highland  -3.852421   
660673         Daylight                Highland  -3.748312   
660674         Daylight                Highland  -3.467828   
660676         Daylight                Highland  -3.862727   
660678         Daylight                Highland  -3.895673   

        Number_of_Casualties  Number_of_Vehicles Road_Surface_Conditions  \
1                          1                   2             Wet or damp   
3                          1                   4                     Dry   
5                          2                   3                     Dry   
6                          1                   2                     Dry   
9                          1                   2                     Dry   
...                      ...                 ...                     ...   
660672                     1                   2                    Snow   
660673                     2                   2             Wet or damp   
660674                     2                   1                     Dry   
660676                     1                   3            Frost or ice   
660678                     1                   1             Wet or damp   

                 Road_Type Urban_or_Rural_Area     Weather_Conditions  \
1       Single carriageway               Urban  Raining no high winds   
3       Single carriageway               Urban     Fine no high winds   
5       Single carriageway               Urban     Fine no high winds   
6         Dual carriageway               Urban     Fine no high winds   
9       Single carriageway               Urban     Fine no high winds   
...                    ...                 ...                    ...   
660672  Single carriageway               Rural     Fine no high winds   
660673  Single carriageway               Rural     Fine no high winds   
660674  Single carriageway               Rural     Fine no high winds   
660676  Single carriageway               Rural     Fine no high winds   
660678    Dual carriageway               Rural  Snowing no high winds   

                                 Vehicle_Type  Year  Month  Day  DayOfWeek  
1                                         Car  2019      7    2          1  
3        Bus or coach (17 or more pass seats)  2021      2   11          3  
5                                         Car  2021      2   11          3  
6         Van / Goods 3.5 tonnes mgw or under  2019      9    5          3  
9       Motorcycle over 125cc and up to 500cc  2021      2   11          3  
...                                       ...   ...    ...  ...        ...  
660672                                    Car  2021      2   11          3  
660673                                    Car  2

<h2>Insight#3
<h3>Theres 484880 that got into an accident in broad daylight

<h2>4.how many that got accident in District Area Kensington and Chelsea	

In [16]:
ukacc[ukacc ['District Area'] == 'Kensington and Chelsea']

Index Accident_Severity Accident Date   Latitude  \
0       200701BS64157           Serious    2019-06-05  51.506187   
1       200701BS65737           Serious    2019-07-02  51.495029   
2       200701BS66127           Serious    2021-02-11  51.517715   
3       200701BS66128           Serious    2021-02-11  51.495478   
4       200701BS66837            Slight    2019-09-03  51.488576   
...               ...               ...           ...        ...   
533088  201001TB00796            Slight    2021-02-11  51.489306   
533316  201001TE00005           Serious    2021-02-11  51.520998   
533327  201001TE00016           Serious    2022-02-02  51.497193   
533337  201001TE00029           Serious    2022-03-12  51.480287   
533342  201001TE00038            Slight    2021-02-11  51.492639   

                   Light_Conditions           District Area  Longitude  \
0             Darkness - lights lit  Kensington and Chelsea  -0.209082   
1                          Daylight  Kensington and Chelsea  -0.173647   
2       Darkness - lighting unknown  Kensington and Chelsea  -0.210215   
3                          Daylight  Kensington and Chelsea  -0.202731   
4             Darkness - lights lit  Kensington and Chelsea  -0.192487   
...                             ...                     ...        ...   
533088        Darkness - lights lit  Kensington and Chelsea  -0.175749   
533316                     Daylight  Kensington and Chelsea  -0.213258   
533327                     Daylight  Kensington and Chelsea  -0.168230   
533337        Darkness - lights lit  Kensington and Chelsea  -0.185614   
533342        Darkness - lights lit  Kensington and Chelsea  -0.187716   

        Number_of_Casualties  Number_of_Vehicles Road_Surface_Conditions  \
0                          1                   2                     Dry   
1                          1                   2             Wet or damp   
2                          1                   3                     Dry   
3                          1                   4                     Dry   
4                          1                   2                     Dry   
...                      ...                 ...                     ...   
533088                     2                   2             Wet or damp   
533316                     1                   1                     Dry   
533327                     1                   2             Wet or damp   
533337                     1                   1                     Dry   
533342                     1                   2             Wet or damp   

                 Road_Type Urban_or_Rural_Area     Weather_Conditions  \
0       Single carriageway               Urban     Fine no high winds   
1       Single carriageway               Urban  Raining no high winds   
2              unaccounted               Urban     Fine no high winds   
3       Single carriageway               Urban     Fine no high winds   
4              unaccounted               Urban     Fine no high winds   
...                    ...                 ...                    ...   
533088  Single carriageway               Urban     Fine no high winds   
533316  Single carriageway               Urban     Fine no high winds   
533327    Dual carriageway               Urban  Raining no high winds   
533337  Single carriageway               Urban     Fine no high winds   
533342          Roundabout               Urban  Raining no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
0                                        Car  2019      6    5          2  
1                                        Car  2019      7    2          1  
2                      Taxi/Private hire car  2021      2   11          3  
3       Bus or coach (17 or more pass seats)  2021      2   11          3  
4                              Other vehicle  2019      9    3          1  
...                                      ...   ...    ...  ...  

<h2>Insight#4
<h3>Theres 2799 that got into an accident in Kensington and Chelsea

<h2>5.how many that got accident in District Area Highland	

In [17]:
ukacc[ukacc ['District Area'] == 'Highland']

Index Accident_Severity Accident Date   Latitude  \
169770  200791NE00016            Slight    2019-01-01  57.793313   
169771  200791NE00427           Serious    2019-01-06  57.808013   
169772  200791NE00428            Slight    2019-01-06  57.780080   
169773  200791NE00744            Slight    2019-01-10  57.479262   
169774  200791NE00798            Slight    2019-01-11  57.264946   
...               ...               ...           ...        ...   
660674  201091NM01760            Slight    2021-02-11  57.374005   
660675  201091NM01881            Slight    2021-02-11  57.232273   
660676  201091NM01935            Slight    2021-02-11  57.585044   
660677  201091NM01964           Serious    2021-02-11  57.214898   
660678  201091NM02142           Serious    2021-02-11  57.575210   

              Light_Conditions District Area  Longitude  Number_of_Casualties  \
169770  Darkness - no lighting      Highland  -4.037324                     1   
169771                Daylight      Highland  -4.045054                     4   
169772                Daylight      Highland  -4.005126                     1   
169773                Daylight      Highland  -6.345396                     1   
169774                Daylight      Highland  -6.080077                     1   
...                        ...           ...        ...                   ...   
660674                Daylight      Highland  -3.467828                     2   
660675  Darkness - no lighting      Highland  -3.809281                     1   
660676                Daylight      Highland  -3.862727                     1   
660677  Darkness - no lighting      Highland  -3.823997                     1   
660678                Daylight      Highland  -3.895673                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
169770                   1             Wet or damp  Single carriageway   
169771                   2            Frost or ice  Single carriageway   
169772                   1            Frost or ice  Single carriageway   
169773                   1                    Snow  Single carriageway   
169774                   1             Wet or damp  Single carriageway   
...                    ...                     ...                 ...   
660674                   1                     Dry  Single carriageway   
660675                   1            Frost or ice  Single carriageway   
660676                   3            Frost or ice  Single carriageway   
660677                   2             Wet or damp  Single carriageway   
660678                   1             Wet or damp    Dual carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
169770               Rural  Raining no high winds   
169771               Rural                  Other   
169772               Rural                  Other   
169773               Rural   Snowing + high winds   
169774               Rural   Raining + high winds   
...                    ...                    ...   
660674               Rural     Fine no high winds   
660675               Rural     Fine no high winds   
660676               Rural     Fine no high winds   
660677               Rural     Fine no high winds   
660678               Rural  Snowing no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
169770  Bus or coach (17 or more pass seats)  2019      1    1          1  
169771   Van / Goods 3.5 tonnes mgw or under  2019      1    6          6  
169772                                   Car  2019      1    6          6  
169773                                   Car  2019      1   10          3  
169774                                   Car  2019      1   11          4  
...                                      ...   ...    ...  ...        ...  
660674                                   Car  2021      2   11          3  
660675                                   Car  2021      2   11          3  
660676          

<h2>Insight#5
<h3>Theres 2021 that got into an accident in Highland

<h2>6.how many that got accident in District Area Westminster

In [18]:
ukacc[ukacc ['District Area'] == 'Westminster']

Index Accident_Severity Accident Date   Latitude  \
51      200701BS70035            Slight    2021-02-11  51.527693   
105     200701BS70092            Slight    2021-02-11  51.501749   
131     200701BS70127            Slight    2021-02-11  51.501910   
171     200701BS70173            Slight    2021-02-11  51.520533   
212     200701BS70218            Slight    2021-02-11  51.527785   
...               ...               ...           ...        ...   
532986  201001TB00647            Slight    2022-10-03  51.511055   
533004  201001TB00669            Slight    2021-02-11  51.520511   
533006  201001TB00671            Slight    2022-10-09  51.511714   
533008  201001TB00673            Slight    2022-10-02  51.517462   
533070  201001TB00765            Slight    2021-02-11  51.520945   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
51      Darkness - lights lit   Westminster  -0.215879                     3   
105     Darkness - lights lit   Westminster  -0.160555                     2   
131                  Daylight   Westminster  -0.159396                     3   
171                  Daylight   Westminster  -0.200447                     1   
212     Darkness - lights lit   Westminster  -0.216020                     1   
...                       ...           ...        ...                   ...   
532986  Darkness - lights lit   Westminster  -0.129195                     1   
533004               Daylight   Westminster  -0.181565                     1   
533006               Daylight   Westminster  -0.188401                     1   
533008               Daylight   Westminster  -0.182119                     1   
533070  Darkness - lights lit   Westminster  -0.180539                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
51                       3                     Dry  Single carriageway   
105                      2                     Dry    Dual carriageway   
131                      2                     Dry  Single carriageway   
171                      1                     Dry  Single carriageway   
212                      2                     Dry  Single carriageway   
...                    ...                     ...                 ...   
532986                   1                     Dry  Single carriageway   
533004                   2             Wet or damp  Single carriageway   
533006                   1                     Dry  Single carriageway   
533008                   2                     Dry  Single carriageway   
533070                   2                     Dry          Roundabout   

       Urban_or_Rural_Area     Weather_Conditions  \
51                   Urban     Fine no high winds   
105                  Urban     Fine no high winds   
131                  Urban     Fine no high winds   
171                  Urban     Fine no high winds   
212                  Urban     Fine no high winds   
...                    ...                    ...   
532986               Urban     Fine no high winds   
533004               Urban  Raining no high winds   
533006               Urban     Fine no high winds   
533008               Urban     Fine no high winds   
533070               Urban     Fine no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
51                     Taxi/Private hire car  2021      2   11          3  
105                                      Car  2021      2   11          3  
131                                      Car  2021      2   11          3  
171     Bus or coach (17 or more pass seats)  2021      2   11          3  
212                                      Car  2021      2   11          3  
...                                      ...   ...    ...  ...        ...  
532986                                   Car  2022     10    3          0  
533004                                   Car  2021      2   11          3  
533006                      

<h2>Insight#6
<h3>Theres 5706 that got into an accident in Westminster

<h2>7.how many that got accident in District Area Tower Hamlets

In [19]:
ukacc[ukacc ['District Area'] == 'Tower Hamlets']

Index Accident_Severity Accident Date   Latitude  \
691     200701CP00001           Serious    2019-01-05  51.509814   
731     200701CP00046            Slight    2021-02-11  51.509078   
765     200701CP00082            Slight    2019-04-01  51.509514   
796     200701CP00113            Slight    2021-02-11  51.510176   
798     200701CP00115            Slight    2021-02-11  51.510176   
...               ...               ...           ...        ...   
533192  201001TC00067            Slight    2021-02-11  51.531730   
533195  201001TC00071            Slight    2021-02-11  51.521651   
533205  201001TC00083           Serious    2021-02-11  51.515414   
533206  201001TC00084           Serious    2022-03-02  51.518341   
533210  201001TC00089            Slight    2021-02-11  51.512375   

             Light_Conditions  District Area  Longitude  Number_of_Casualties  \
691     Darkness - lights lit  Tower Hamlets  -0.074771                     1   
731     Darkness - lights lit  Tower Hamlets  -0.073793                     1   
765                  Daylight  Tower Hamlets  -0.078387                     1   
796                  Daylight  Tower Hamlets  -0.074900                     1   
798                  Daylight  Tower Hamlets  -0.074900                     1   
...                       ...            ...        ...                   ...   
533192               Daylight  Tower Hamlets  -0.035205                     1   
533195               Daylight  Tower Hamlets  -0.018773                     1   
533205  Darkness - lights lit  Tower Hamlets  -0.070787                     1   
533206  Darkness - lights lit  Tower Hamlets  -0.062880                     1   
533210               Daylight  Tower Hamlets  -0.034021                     2   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
691                      3             Wet or damp    Dual carriageway   
731                      2                     Dry    Dual carriageway   
765                      2                     Dry    Dual carriageway   
796                      2                     Dry  Single carriageway   
798                      2                     Dry    Dual carriageway   
...                    ...                     ...                 ...   
533192                   2             Wet or damp  Single carriageway   
533195                   2                     Dry          Roundabout   
533205                   1                     Dry      One way street   
533206                   2                     Dry  Single carriageway   
533210                   1                     Dry  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
691                  Urban     Fine no high winds   
731                  Urban     Fine no high winds   
765                  Urban     Fine no high winds   
796                  Urban     Fine no high winds   
798                  Urban     Fine no high winds   
...                    ...                    ...   
533192               Urban  Raining no high winds   
533195               Urban     Fine no high winds   
533205               Urban     Fine no high winds   
533206               Urban     Fine no high winds   
533210               Urban     Fine no high winds   

                                 Vehicle_Type  Year  Month  Day  DayOfWeek  
691                Motorcycle 125cc and under  2019      1    5          5  
731                                       Car  2021      2   11          3  
765                     Taxi/Private hire car  2019      4    1          0  
796     Motorcycle over 125cc and up to 500cc  2021      2   11          3  
798                                       Car  2021      2   11          3  
...                                       ...   ...    ...  ...        ...  
533192                                    Car  2021      2   11          3  
533195                                    Car  2021      2   11          3  
533205 

<h2>Insight#7
<h3>Theres 3341 that got into an accident in Tower Hamlets

<h2>8.how many that got accident in District Area City of London

In [20]:
ukacc[ukacc ['District Area'] == 'City of London']

Index Accident_Severity Accident Date   Latitude  \
692     200701CP00003            Slight    2019-01-08  51.510898   
693     200701CP00006            Slight    2021-02-11  51.515721   
694     200701CP00007            Slight    2021-02-11  51.509123   
695     200701CP00008           Serious    2021-02-11  51.518599   
696     200701CP00010            Slight    2021-02-11  51.508932   
...               ...               ...           ...        ...   
522150  201001HT20829            Slight    2022-11-05  51.514113   
522172  201001HT20857            Slight    2022-12-01  51.511039   
527028  201001MM70780            Slight    2021-02-11  51.504618   
532401  201001TA00322           Serious    2022-10-03  51.510053   
532454  201001TA00400            Slight    2022-11-11  51.510153   

             Light_Conditions   District Area  Longitude  \
692                  Daylight  City of London  -0.102684   
693                  Daylight  City of London  -0.100610   
694     Darkness - lights lit  City of London  -0.087482   
695                  Daylight  City of London  -0.100634   
696     Darkness - lights lit  City of London  -0.081293   
...                       ...             ...        ...   
522150               Daylight  City of London  -0.073725   
522172               Daylight  City of London  -0.072702   
527028               Daylight  City of London  -0.075999   
532401  Darkness - lights lit  City of London  -0.072887   
532454  Darkness - lights lit  City of London  -0.090033   

        Number_of_Casualties  Number_of_Vehicles Road_Surface_Conditions  \
692                        1                   2                     Dry   
693                        1                   2             Wet or damp   
694                        1                   2             Wet or damp   
695                        1                   1             Wet or damp   
696                        2                   2                     Dry   
...                      ...                 ...                     ...   
522150                     1                   1                     Dry   
522172                     1                   1                     Dry   
527028                     1                   2                     Dry   
532401                     1                   1                     Dry   
532454                     1                   2             Wet or damp   

                 Road_Type Urban_or_Rural_Area     Weather_Conditions  \
692       Dual carriageway               Urban     Fine no high winds   
693     Single carriageway               Urban  Raining no high winds   
694       Dual carriageway               Urban   Raining + high winds   
695     Single carriageway               Urban  Raining no high winds   
696       Dual carriageway               Urban     Fine no high winds   
...                    ...                 ...                    ...   
522150  Single carriageway               Urban     Fine no high winds   
522172  Single carriageway               Urban     Fine no high winds   
527028  Single carriageway               Urban     Fine no high winds   
532401  Single carriageway               Urban     Fine no high winds   
532454  Single carriageway               Urban     Fine no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
692      Van / Goods 3.5 tonnes mgw or under  2019      1    8          1  
693                    Taxi/Private hire car  2021      2   11          3  
694      Van / Goods 3.5 tonnes mgw or under  2021      2   11          3  
695               Motorcycle 125cc and under  2021      2   11          3  
696     Bus or coach (17 or more pass seats)  2021      2   11          3  
...                                      ...   ...    ...  ...        ...  
522150  Bus or coach (17 or more pass seats)  2022     11    5          5  
522172             Motorcycle 50cc and under  2022     12    1          3  
5270

<h2>Insight#8
<h3>Theres 1317 that got into an accident in City of London

<h2>9.how many that got accident in District Area Camden

In [21]:
ukacc[ukacc ['District Area'] == 'Camden']

Index Accident_Severity Accident Date   Latitude  \
772     200701CP00089            Slight    2021-02-11  51.518494   
829     200701CP00146            Slight    2021-02-11  51.518494   
888     200701CP00206            Slight    2019-08-07  51.518409   
942     200701CP00261            Slight    2021-02-11  51.518409   
1058    200701CW10035           Serious    2021-02-11  51.535720   
...               ...               ...           ...        ...   
533082  201001TB00787           Serious    2021-02-11  51.541995   
533091  201001TB00799           Serious    2021-02-11  51.521412   
533105  201001TB00820            Slight    2021-02-11  51.529648   
533123  201001TB00843           Serious    2021-02-11  51.517166   
533137  201001TB00915            Slight    2021-02-11  51.555222   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
772                  Daylight        Camden  -0.105251                     1   
829                  Daylight        Camden  -0.105251                     1   
888     Darkness - lights lit        Camden  -0.105543                     1   
942     Darkness - lights lit        Camden  -0.105543                     3   
1058    Darkness - lights lit        Camden  -0.164953                     1   
...                       ...           ...        ...                   ...   
533082  Darkness - lights lit        Camden  -0.146530                     1   
533091  Darkness - lights lit        Camden  -0.113347                     2   
533105               Daylight        Camden  -0.133479                     1   
533123  Darkness - lights lit        Camden  -0.123323                     3   
533137  Darkness - lights lit        Camden  -0.193164                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
772                      3                     Dry  Single carriageway   
829                      2             Wet or damp  Single carriageway   
888                      2             Wet or damp  Single carriageway   
942                      2                     Dry  Single carriageway   
1058                     2                     Dry  Single carriageway   
...                    ...                     ...                 ...   
533082                   1                     Dry  Single carriageway   
533091                   2                     Dry  Single carriageway   
533105                   1                     Dry  Single carriageway   
533123                   1                     Dry  Single carriageway   
533137                   1                     Dry  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
772                  Urban     Fine no high winds   
829                  Urban     Fine no high winds   
888                  Urban  Raining no high winds   
942                  Urban     Fine no high winds   
1058                 Urban     Fine no high winds   
...                    ...                    ...   
533082               Urban     Fine no high winds   
533091               Urban     Fine no high winds   
533105               Urban     Fine no high winds   
533123               Urban     Fine no high winds   
533137               Urban     Fine no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
772               Motorcycle 125cc and under  2021      2   11          3  
829      Van / Goods 3.5 tonnes mgw or under  2021      2   11          3  
888                                      Car  2019      8    7          2  
942            Goods 7.5 tonnes mgw and over  2021      2   11          3  
1058     Van / Goods 3.5 tonnes mgw or under  2021      2   11          3  
...                                      ...   ...    ...  ...        ...  
533082                 Motorcycle over 500cc  2021      2   11          3  
533091                 Motorcycle over 500cc  2021      2   11          3  
533105                      

<h2>Insight#9
<h3>Theres 3148 that got into an accident in Camden

<h2>10.how many that got accident in District Area Barnet

In [22]:
ukacc[ukacc ['District Area'] == 'Barnet']

Index Accident_Severity Accident Date   Latitude  \
1539    200701CW10624            Slight    2019-05-04  51.580847   
12400   200701QA10008            Slight    2021-02-11  51.632153   
12451   200701QA10084            Slight    2021-02-11  51.597479   
12460   200701QA10097            Slight    2021-02-11  51.619447   
12492   200701QA10140           Serious    2021-02-11  51.602146   
...               ...               ...           ...        ...   
533085  201001TB00792           Serious    2021-02-11  51.613395   
533095  201001TB00805            Slight    2021-02-11  51.596934   
533112  201001TB00829            Slight    2022-12-05  51.646312   
533152  201001TC00019           Serious    2021-02-11  51.589470   
536087  201001XD80076           Serious    2021-02-11  51.621160   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
1539                 Daylight        Barnet  -0.198787                     1   
12400   Darkness - lights lit        Barnet  -0.304695                     1   
12451   Darkness - lights lit        Barnet  -0.264114                     1   
12460   Darkness - lights lit        Barnet  -0.290434                     1   
12492                Daylight        Barnet  -0.269568                     1   
...                       ...           ...        ...                   ...   
533085  Darkness - lights lit        Barnet  -0.282428                     1   
533095               Daylight        Barnet  -0.198150                     1   
533112               Daylight        Barnet  -0.187087                     1   
533152  Darkness - lights lit        Barnet  -0.221688                     2   
536087  Darkness - lights lit        Barnet  -0.254109                     2   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
1539                     2                     Dry  Single carriageway   
12400                    1             Wet or damp  Single carriageway   
12451                    2                     Dry  Single carriageway   
12460                    2                     Dry  Single carriageway   
12492                    1                     Dry  Single carriageway   
...                    ...                     ...                 ...   
533085                   1             Wet or damp  Single carriageway   
533095                   2             Wet or damp  Single carriageway   
533112                   1                     Dry  Single carriageway   
533152                   2                     Dry  Single carriageway   
536087                   3             Wet or damp    Dual carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
1539                 Urban     Fine no high winds   
12400                Rural  Raining no high winds   
12451                Urban     Fine no high winds   
12460                Urban     Fine no high winds   
12492                Urban     Fine no high winds   
...                    ...                    ...   
533085               Urban                  Other   
533095               Urban     Fine no high winds   
533112               Urban     Fine no high winds   
533152               Urban     Fine no high winds   
536087               Urban  Raining no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
1539                   Motorcycle over 500cc  2019      5    4          5  
12400                                    Car  2021      2   11          3  
12451                                    Car  2021      2   11          3  
12460                                    Car  2021      2   11          3  
12492   Bus or coach (17 or more pass seats)  2021      2   11          3  
...                                      ...   ...    ...  ...        ...  
533085  Bus or coach (17 or more pass seats)  2021      2   11          3  
533095                                   Car  2021      2   11          3  
533112                      

<h2>Insight#10
<h3>Theres 4350 that got into an accident in Barnet

<h2>11.how many that got accident in District Area Brent

In [23]:
ukacc[ukacc ['District Area'] == 'Brent']

Index Accident_Severity Accident Date   Latitude  \
1723    200701CW10845            Slight    2019-09-03  51.532841   
1993    200701CW11188            Slight    2021-02-11  51.532844   
2052    200701CW11271            Slight    2019-11-09  51.532107   
2546    200701EK63172           Serious    2021-02-11  51.550132   
2653    200701EK65649            Slight    2019-07-03  51.552335   
...               ...               ...           ...        ...   
533111  201001TB00828           Serious    2021-02-11  51.595146   
533119  201001TB00839            Slight    2022-12-08  51.553458   
533120  201001TB00840           Serious    2021-02-11  51.550225   
533126  201001TB00846            Slight    2022-12-08  51.548212   
533135  201001TB00885            Slight    2021-02-11  51.544818   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
1723                 Daylight         Brent  -0.205585                     1   
1993                 Daylight         Brent  -0.205729                     1   
2052                 Daylight         Brent  -0.192926                     1   
2546                 Daylight         Brent  -0.207212                     1   
2653                 Daylight         Brent  -0.210155                     1   
...                       ...           ...        ...                   ...   
533111               Daylight         Brent  -0.282828                     1   
533119               Daylight         Brent  -0.212996                     2   
533120               Daylight         Brent  -0.261154                     1   
533126  Darkness - lights lit         Brent  -0.240750                     1   
533135               Daylight         Brent  -0.272609                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
1723                     1                     Dry  Single carriageway   
1993                     1                     Dry  Single carriageway   
2052                     2                     Dry          Roundabout   
2546                     3                     Dry  Single carriageway   
2653                     2                     Dry  Single carriageway   
...                    ...                     ...                 ...   
533111                   1                     Dry  Single carriageway   
533119                   2                     Dry  Single carriageway   
533120                   1             Wet or damp  Single carriageway   
533126                   2                     Dry  Single carriageway   
533135                   2             Wet or damp    Dual carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
1723                 Urban     Fine no high winds   
1993                 Urban     Fine no high winds   
2052                 Urban     Fine no high winds   
2546                 Urban     Fine no high winds   
2653                 Urban     Fine no high winds   
...                    ...                    ...   
533111               Urban                  Other   
533119               Urban     Fine no high winds   
533120               Urban  Raining no high winds   
533126               Urban     Fine no high winds   
533135               Urban                  Other   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
1723    Bus or coach (17 or more pass seats)  2019      9    3          1  
1993                                     Car  2021      2   11          3  
2052                                     Car  2019     11    9          5  
2546                                     Car  2021      2   11          3  
2653                                     Car  2019      7    3          2  
...                                      ...   ...    ...  ...        ...  
533111                                   Car  2021      2   11          3  
533119             Motorcycle 50cc and under  2022     12    8          3  
533120                      

<h2>Insight#11
<h3>Theres 2857 that got into an accident in Brent

<h2>12.how many that got accident in District Area Islington

In [24]:
ukacc[ukacc ['District Area'] == 'Islington']

Index Accident_Severity Accident Date   Latitude  \
1032    200701CP00353           Serious    2019-12-07  51.520363   
2486    200701EK40674            Slight    2021-02-11  51.564529   
2489    200701EK62180            Slight    2021-02-11  51.528823   
2493    200701EK62258            Slight    2021-02-11  51.542158   
2606    200701EK64714           Serious    2021-02-11  51.548732   
...               ...               ...           ...        ...   
538642  201001YR90319            Slight    2022-05-02  51.566555   
538664  201001YR90345            Slight    2021-02-11  51.570556   
538701  201001YR90391            Slight    2022-06-08  51.574964   
538747  201001YR90446            Slight    2022-07-05  51.574964   
538935  201001YR90667            Slight    2021-02-11  51.566827   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
1032    Darkness - lights lit     Islington  -0.087443                     1   
2486                 Daylight     Islington  -0.104781                     1   
2489                 Daylight     Islington  -0.115635                     1   
2493                 Daylight     Islington  -0.117248                     1   
2606                 Daylight     Islington  -0.129092                     1   
...                       ...           ...        ...                   ...   
538642               Daylight     Islington  -0.107726                     1   
538664               Daylight     Islington  -0.138586                     1   
538701               Daylight     Islington  -0.121809                     1   
538747               Daylight     Islington  -0.121809                     1   
538935               Daylight     Islington  -0.107859                     2   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
1032                     2                     Dry  Single carriageway   
2486                     1                     Dry  Single carriageway   
2489                     2                     Dry      One way street   
2493                     2                     Dry  Single carriageway   
2606                     1             Wet or damp      One way street   
...                    ...                     ...                 ...   
538642                   1                     Dry  Single carriageway   
538664                   2                     Dry    Dual carriageway   
538701                   2                     Dry          Roundabout   
538747                   2                     Dry  Single carriageway   
538935                   2                     Dry  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
1032                 Urban     Fine no high winds   
2486                 Urban     Fine no high winds   
2489                 Urban     Fine no high winds   
2493                 Urban     Fine no high winds   
2606                 Urban  Raining no high winds   
...                    ...                    ...   
538642               Urban     Fine no high winds   
538664               Urban     Fine no high winds   
538701               Urban     Fine no high winds   
538747               Urban     Fine no high winds   
538935               Urban     Fine no high winds   

                                 Vehicle_Type  Year  Month  Day  DayOfWeek  
1032     Bus or coach (17 or more pass seats)  2019     12    7          5  
2486     Bus or coach (17 or more pass seats)  2021      2   11          3  
2489                                      Car  2021      2   11          3  
2493                                      Car  2021      2   11          3  
2606    Motorcycle over 125cc and up to 500cc  2021      2   11          3  
...                                       ...   ...    ...  ...        ...  
538642  Motorcycle over 125cc and up to 500cc  2022      5    2          0  
538664                                    Car  2021      2   11          3  
538701             

<h2>Insight#12
<h3>Theres 2657 that got into an accident in Islington

<h2>13.how many that got accident in District Area Hackney

In [25]:
ukacc[ukacc ['District Area'] == 'Hackney']

Index Accident_Severity Accident Date   Latitude  \
774     200701CP00091            Slight    2019-04-12  51.521877   
2532    200701EK62827            Slight    2021-02-11  51.532772   
3126    200701EO40508            Slight    2019-09-01  51.546193   
3285    200701EO40688            Slight    2021-02-11  51.546214   
3493    200701EO40933            Slight    2021-02-11  51.539490   
...               ...               ...           ...        ...   
538574  201001YR90237           Serious    2022-03-04  51.574833   
538622  201001YR90297            Slight    2022-05-07  51.574833   
538728  201001YR90423           Serious    2021-02-11  51.552830   
538771  201001YR90474            Slight    2022-07-02  51.570592   
538953  201001YR90686            Slight    2022-10-09  51.574923   

       Light_Conditions District Area  Longitude  Number_of_Casualties  \
774            Daylight       Hackney  -0.081037                     1   
2532           Daylight       Hackney  -0.087356                     1   
3126           Daylight       Hackney  -0.077707                     2   
3285           Daylight       Hackney  -0.079004                     1   
3493           Daylight       Hackney  -0.085776                     1   
...                 ...           ...        ...                   ...   
538574         Daylight       Hackney  -0.085879                     1   
538622         Daylight       Hackney  -0.085879                     2   
538728         Daylight       Hackney  -0.087669                     1   
538771         Daylight       Hackney  -0.096014                     1   
538953         Daylight       Hackney  -0.085875                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
774                      2                     Dry  Single carriageway   
2532                     2                     Dry    Dual carriageway   
3126                     3                     Dry  Single carriageway   
3285                     1                     Dry  Single carriageway   
3493                     2                     Dry  Single carriageway   
...                    ...                     ...                 ...   
538574                   2                     Dry  Single carriageway   
538622                   2                     Dry  Single carriageway   
538728                   2                     Dry  Single carriageway   
538771                   2                     Dry    Dual carriageway   
538953                   2                     Dry  Single carriageway   

       Urban_or_Rural_Area  Weather_Conditions  \
774                  Urban  Fine no high winds   
2532                 Urban  Fine no high winds   
3126                 Urban  Fine no high winds   
3285                 Urban  Fine no high winds   
3493                 Urban  Fine no high winds   
...                    ...                 ...   
538574               Urban  Fine no high winds   
538622               Urban  Fine no high winds   
538728               Urban  Fine no high winds   
538771               Urban  Fine no high winds   
538953               Urban  Fine no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
774               Motorcycle 125cc and under  2019      4   12          4  
2532              Motorcycle 125cc and under  2021      2   11          3  
3126    Bus or coach (17 or more pass seats)  2019      9    1          6  
3285                                     Car  2021      2   11          3  
3493                   Motorcycle over 500cc  2021      2   11          3  
...                                      ...   ...    ...  ...        ...  
538574                                   Car  2022      3    4          4  
538622                                   Car  2022      5    7          5  
538728   Van / Goods 3.5 tonnes mgw or under  2021      2   11          3  
538771         Goods 7.5 tonnes mgw and over  2022      7   

<h2>Insight#13
<h3>Theres 3207 that got into an accident in Hackney

<h2>14.how many that got accident in District Area Hounslow

In [26]:
ukacc[ukacc ['District Area'] == 'Hounslow']

Index Accident_Severity Accident Date   Latitude  \
402     200701BS70420            Slight    2019-08-07  51.487150   
3692    200701FH10140            Slight    2021-02-11  51.476270   
16106   200701TE00004           Serious    2021-02-11  51.461120   
16114   200701TE00013           Serious    2021-02-11  51.468560   
16116   200701TE00015            Slight    2021-02-11  51.463022   
...               ...               ...           ...        ...   
536291  201001XD80325            Slight    2021-02-11  51.494927   
536320  201001XD80356            Slight    2021-02-11  51.494670   
536577  201001XD80660            Slight    2022-09-02  51.499176   
536926  201001XH30096            Slight    2022-02-06  51.498639   
537138  201001XH30360            Slight    2022-05-05  51.491110   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
402                  Daylight      Hounslow  -0.252608                     1   
3692    Darkness - lights lit      Hounslow  -0.384355                     1   
16106                Daylight      Hounslow  -0.374813                     1   
16114   Darkness - lights lit      Hounslow  -0.347337                     1   
16116   Darkness - lights lit      Hounslow  -0.415199                     1   
...                       ...           ...        ...                   ...   
536291               Daylight      Hounslow  -0.387441                     1   
536320  Darkness - lights lit      Hounslow  -0.305479                     1   
536577               Daylight      Hounslow  -0.408902                     1   
536926               Daylight      Hounslow  -0.409065                     1   
537138               Daylight      Hounslow  -0.410912                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
402                      2                     Dry          Roundabout   
3692                     2                     Dry    Dual carriageway   
16106                    1             Wet or damp  Single carriageway   
16114                    1                     Dry  Single carriageway   
16116                    3             Wet or damp  Single carriageway   
...                    ...                     ...                 ...   
536291                   2                     Dry  Single carriageway   
536320                   1                     Dry  Single carriageway   
536577                   2                     Dry    Dual carriageway   
536926                   2                     Dry    Dual carriageway   
537138                   3                     Dry    Dual carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
402                  Urban     Fine no high winds   
3692                 Urban     Fine no high winds   
16106                Urban  Raining no high winds   
16114                Urban     Fine no high winds   
16116                Urban     Fine no high winds   
...                    ...                    ...   
536291               Urban     Fine no high winds   
536320               Urban     Fine no high winds   
536577               Urban     Fine no high winds   
536926               Urban     Fine no high winds   
537138               Urban     Fine no high winds   

                                Vehicle_Type  Year  Month  Day  DayOfWeek  
402                                      Car  2019      8    7          2  
3692                                     Car  2021      2   11          3  
16106   Bus or coach (17 or more pass seats)  2021      2   11          3  
16114                                    Car  2021      2   11          3  
16116    Van / Goods 3.5 tonnes mgw or under  2021      2   11          3  
...                                      ...   ...    ...  ...        ...  
536291                                   Car  2021      2   11          3  
536320                                   Car  2021      2   11          3  
536577                      

<h2>Insight#14
<h3>Theres 2979 that got into an accident in Hounslow

<h2>15.how many that got accident in District Area merton

In [27]:
ukacc[ukacc ['District Area'] == 'Merton']

Index Accident_Severity Accident Date   Latitude  \
3746    200701FH10200           Serious    2021-02-11  51.426251   
9671    200701LX62694            Slight    2021-02-11  51.426061   
16111   200701TE00010             Fatal    2019-02-04  51.405966   
16115   200701TE00014            Slight    2021-02-11  51.417809   
16117   200701TE00016           Serious    2019-02-10  51.431057   
...               ...               ...           ...        ...   
535163  201001VW49003            Slight    2021-02-11  51.401223   
535165  201001VW49089            Slight    2022-11-09  51.416056   
535166  201001VW49091            Slight    2021-02-11  51.400498   
535984  201001WW50979            Slight    2021-02-11  51.420022   
539543  201001ZD30499            Slight    2022-05-11  51.397947   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
3746                 Daylight        Merton  -0.197968                     1   
9671                 Daylight        Merton  -0.203154                     1   
16111   Darkness - lights lit        Merton  -0.165696                     2   
16115                Daylight        Merton  -0.192835                     1   
16117                Daylight        Merton  -0.212310                     2   
...                       ...           ...        ...                   ...   
535163               Daylight        Merton  -0.237483                     2   
535165               Daylight        Merton  -0.184132                     1   
535166  Darkness - lights lit        Merton  -0.143918                     1   
535984  Darkness - lights lit        Merton  -0.161681                     1   
539543               Daylight        Merton  -0.124901                     2   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
3746                     2                     Dry  Single carriageway   
9671                     2                     Dry  Single carriageway   
16111                    1                     Dry    Dual carriageway   
16115                    3                     Dry  Single carriageway   
16117                    2             Wet or damp  Single carriageway   
...                    ...                     ...                 ...   
535163                   2                     Dry  Single carriageway   
535165                   1             Wet or damp  Single carriageway   
535166                   1             Wet or damp  Single carriageway   
535984                   3                     Dry      One way street   
539543                   2                     Dry  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
3746                 Urban     Fine no high winds   
9671                 Urban     Fine no high winds   
16111                Urban     Fine no high winds   
16115                Urban     Fine no high winds   
16117                Urban  Raining no high winds   
...                    ...                    ...   
535163               Urban     Fine no high winds   
535165               Urban  Raining no high winds   
535166               Urban     Fine no high winds   
535984               Urban     Fine no high winds   
539543               Urban     Fine no high winds   

                                 Vehicle_Type  Year  Month  Day  DayOfWeek  
3746                                      Car  2021      2   11          3  
9671                                      Car  2021      2   11          3  
16111   Motorcycle over 125cc and up to 500cc  2019      2    4          0  
16115                                     Car  2021      2   11          3  
16117                                     Car  2019      2   10          6  
...                                       ...   ...    ...  ...        ...  
535163                                    Car  2021      2   11          3  
535165                                    Car  2022     11    9          2  
535166             

<h2>Insight#15
<h3>Theres 1639 that got into an accident in merton

<h2>15.how many that got accident in District Area Bedford

In [28]:
ukacc[ukacc ['District Area'] == 'Bedford']

Index Accident_Severity Accident Date   Latitude  \
107645  2007400B00016             Fatal    2021-02-11  52.129772   
107647  2007400B00074            Slight    2021-02-11  52.138891   
107648  2007400B00082            Slight    2019-01-05  52.159171   
107649  2007400B00087            Slight    2021-02-11  52.124101   
107650  2007400B00098           Serious    2019-01-08  52.113664   
...               ...               ...           ...        ...   
610189  2010400B03771           Serious    2021-02-11  52.140317   
610192  2010400B25208           Serious    2021-02-11  52.207784   
611050  2010400D01975            Slight    2021-02-11  52.069091   
611091  2010400D02204            Slight    2021-02-11  52.193926   
611295  201040E859101            Slight    2021-02-11  52.313125   

              Light_Conditions District Area  Longitude  Number_of_Casualties  \
107645                Daylight       Bedford  -0.414730                     5   
107647   Darkness - lights lit       Bedford  -0.465113                     1   
107648                Daylight       Bedford  -0.427867                     1   
107649   Darkness - lights lit       Bedford  -0.420921                     1   
107650   Darkness - lights lit       Bedford  -0.510232                     2   
...                        ...           ...        ...                   ...   
610189                Daylight       Bedford  -0.443582                     1   
610192  Darkness - no lighting       Bedford  -0.283745                     2   
611050                Daylight       Bedford  -0.449416                     4   
611091                Daylight       Bedford  -0.514865                     1   
611295                Daylight       Bedford  -0.443102                     2   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
107645                   1                     Dry    Dual carriageway   
107647                   2             Wet or damp  Single carriageway   
107648                   1             Wet or damp  Single carriageway   
107649                   3             Wet or damp          Roundabout   
107650                   2             Wet or damp  Single carriageway   
...                    ...                     ...                 ...   
610189                   1            Frost or ice  Single carriageway   
610192                   2                     Dry  Single carriageway   
611050                   7                     Dry  Single carriageway   
611091                   1             Wet or damp  Single carriageway   
611295                   1                     Dry  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
107645               Rural     Fine no high winds   
107647               Urban     Fine no high winds   
107648               Urban     Fine no high winds   
107649               Rural     Fine no high winds   
107650               Rural  Raining no high winds   
...                    ...                    ...   
610189               Urban     Fine no high winds   
610192               Rural     Fine no high winds   
611050               Rural     Fine no high winds   
611091               Rural  Raining no high winds   
611295               Rural     Fine no high winds   

                                 Vehicle_Type  Year  Month  Day  DayOfWeek  
107645                                    Car  2021      2   11          3  
107647                                    Car  2021      2   11          3  
107648                                    Car  2019      1    5          5  
107649                                    Car  2021      2   11          3  
107650  Motorcycle over 125cc and up to 500cc  2019      1    8          1  
...                                       ...   ...    ...  ...        ...  
610189                                    Car  2021      2   11          3  
610192                                    Car  2021      2   11          3  
611050 

<h2>Insight#15
<h3>Theres 1728 that got into an accident in merton

<h2>16.how many that got accident in District Area Gosport

In [29]:
ukacc[ukacc ['District Area'] == 'Gosport']

Index Accident_Severity Accident Date   Latitude  \
124824  2.01E+12            Slight    2019-01-01  50.798229   
124841  2.01E+12            Slight    2019-01-03  50.810923   
124857  2.01E+12            Slight    2019-01-03  50.815049   
124860  2.01E+12            Slight    2019-01-05  50.810693   
124907  2.01E+12            Slight    2019-01-08  50.806287   
...          ...               ...           ...        ...   
628292  2.01E+12            Slight    2021-02-11  50.809496   
628303  2.01E+12            Slight    2021-02-11  50.808418   
628319  2.01E+12            Slight    2021-02-11  50.810908   
628352  2.01E+12            Slight    2021-02-11  50.813325   
628380  2.01E+12            Slight    2021-02-11  50.792137   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
124824               Daylight       Gosport  -1.166749                     1   
124841               Daylight       Gosport  -1.156161                     2   
124857  Darkness - lights lit       Gosport  -1.167159                     1   
124860               Daylight       Gosport  -1.137004                     1   
124907               Daylight       Gosport  -1.149291                     1   
...                       ...           ...        ...                   ...   
628292               Daylight       Gosport  -1.196070                     1   
628303  Darkness - lights lit       Gosport  -1.145562                     1   
628319               Daylight       Gosport  -1.154174                     1   
628352               Daylight       Gosport  -1.140362                     2   
628380  Darkness - lights lit       Gosport  -1.145149                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
124824                   2             Wet or damp  Single carriageway   
124841                   2                     Dry  Single carriageway   
124857                   1                     Dry  Single carriageway   
124860                   2                     Dry  Single carriageway   
124907                   3             Wet or damp  Single carriageway   
...                    ...                     ...                 ...   
628292                   1                     Dry  Single carriageway   
628303                   1             Wet or damp  Single carriageway   
628319                   2            Frost or ice  Single carriageway   
628352                   2                     Dry  Single carriageway   
628380                   2             Wet or damp  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions                Vehicle_Type  \
124824               Urban  Raining no high winds                         Car   
124841               Urban     Fine no high winds                         Car   
124857               Urban     Fine no high winds                         Car   
124860               Urban     Fine no high winds                         Car   
124907               Urban     Fine no high winds                         Car   
...                    ...                    ...                         ...   
628292               Urban     Fine no high winds                         Car   
628303               Urban      Fine + high winds                         Car   
628319               Urban  Snowing no high winds  Motorcycle 125cc and under   
628352               Urban     Fine no high winds                         Car   
628380               Urban  Raining no high winds                         Car   

        Year  Month  Day  DayOfWeek  
124824  2019      1    1          1  
124841  2019      1    3          3  
124857  2019      1    3          3  
124860  2019      1    5          5  
124907  2019      1    8          1  
...      ...    ...  ...        ...  
628292  2021      2   11          3  
628303  2021      2   11          3  
628319  2021      2   11          3  
628352  2021      2   11          3  
628380  2021 

<h2>Insight#16
<h3>Theres 695 that got into an accident in Gosport

<h2>17.how many that got accident in District Area Hart

In [30]:
ukacc[ukacc ['District Area'] == 'Hart']

Index Accident_Severity Accident Date   Latitude  \
124819  2.01E+12            Slight    2019-01-02  51.336516   
124834  2.01E+12            Slight    2019-01-02  51.332247   
124854  2.01E+12            Slight    2019-01-04  51.321438   
124870  2.01E+12            Slight    2019-01-05  51.359485   
124891  2.01E+12            Slight    2019-01-06  51.278757   
...          ...               ...           ...        ...   
628334  2.01E+12            Slight    2021-02-11  51.296970   
628358  2.01E+12            Slight    2021-02-11  51.240078   
628368  2.01E+12            Slight    2021-02-11  51.260320   
628372  2.01E+12            Slight    2021-02-11  51.268842   
628373  2.01E+12            Slight    2021-02-11  51.273769   

              Light_Conditions District Area  Longitude  Number_of_Casualties  \
124819   Darkness - lights lit          Hart  -0.803016                     1   
124834   Darkness - lights lit          Hart  -0.781452                     2   
124854                Daylight          Hart  -0.869280                     1   
124870  Darkness - no lighting          Hart  -0.967735                     1   
124891   Darkness - lights lit          Hart  -0.844951                     1   
...                        ...           ...        ...                   ...   
628334   Darkness - lights lit          Hart  -0.831728                     1   
628358                Daylight          Hart  -0.825721                     1   
628368  Darkness - no lighting          Hart  -0.826638                     1   
628372   Darkness - lights lit          Hart  -0.833588                     1   
628373   Darkness - lights lit          Hart  -0.849807                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
124819                   2             Wet or damp  Single carriageway   
124834                   1                     Dry  Single carriageway   
124854                   1             Wet or damp    Dual carriageway   
124870                   2             Wet or damp  Single carriageway   
124891                   1                     Dry  Single carriageway   
...                    ...                     ...                 ...   
628334                   2            Frost or ice          Roundabout   
628358                   1                     Dry  Single carriageway   
628368                   1             Wet or damp  Single carriageway   
628372                   2             Wet or damp  Single carriageway   
628373                   2             Wet or damp  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
124819               Rural     Fine no high winds   
124834               Urban     Fine no high winds   
124854               Rural     Fine no high winds   
124870               Rural  Raining no high winds   
124891               Urban     Fine no high winds   
...                    ...                    ...   
628334               Rural     Fine no high winds   
628358               Rural     Fine no high winds   
628368               Urban            Fog or mist   
628372               Urban     Fine no high winds   
628373               Urban     Fine no high winds   

                         Vehicle_Type  Year  Month  Day  DayOfWeek  
124819                            Car  2019      1    2          2  
124834                            Car  2019      1    2          2  
124854                            Car  2019      1    4          4  
124870                            Car  2019      1    5          5  
124891                            Car  2019      1    6          6  
...                               ...   ...    ...  ...        ...  
628334                            Car  2021      2   11          3  
628358                            Car  2021      2   11          3  
628368                            Car  2021      2   11          3  
628372                            Car  2021      2   11          

<h2>Insight#16
<h3>Theres 820 that got into an accident in Hart

<h2>17.how many that got accident in District Area Test Valley

In [31]:
ukacc[ukacc ['District Area'] == 'Test Valley']

Index Accident_Severity Accident Date   Latitude  \
124812  2.01E+12            Slight    2019-01-01  51.000909   
124822  2.01E+12            Slight    2019-01-02  51.132905   
124823  2.01E+12            Slight    2019-01-02  51.066701   
124827  2.01E+12           Serious    2019-01-02  50.963386   
124862  2.01E+12            Slight    2019-01-05  51.140931   
...          ...               ...           ...        ...   
628282  2.01E+12            Slight    2021-02-11  50.950652   
628293  2.01E+12            Slight    2021-02-11  51.215123   
628361  2.01E+12            Slight    2021-02-11  51.211282   
628363  2.01E+12            Slight    2021-02-11  50.945031   
628364  2.01E+12            Slight    2021-02-11  51.222999   

              Light_Conditions District Area  Longitude  Number_of_Casualties  \
124812                Daylight   Test Valley  -1.472810                     1   
124822                Daylight   Test Valley  -1.606511                     1   
124823                Daylight   Test Valley  -1.551127                     1   
124827                Daylight   Test Valley  -1.393633                     2   
124862                Daylight   Test Valley  -1.383019                     1   
...                        ...           ...        ...                   ...   
628282                Daylight   Test Valley  -1.475229                     1   
628293   Darkness - lights lit   Test Valley  -1.476380                     3   
628361  Darkness - no lighting   Test Valley  -1.571198                     1   
628363                Daylight   Test Valley  -1.485256                     1   
628364                Daylight   Test Valley  -1.468129                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
124812                   3                     Dry  Single carriageway   
124822                   1                     Dry  Single carriageway   
124823                   1                     Dry  Single carriageway   
124827                   2                     Dry  Single carriageway   
124862                   2             Wet or damp  Single carriageway   
...                    ...                     ...                 ...   
628282                   3                     Dry    Dual carriageway   
628293                   2             Wet or damp  Single carriageway   
628361                   1                     Dry    Dual carriageway   
628363                   3             Wet or damp    Dual carriageway   
628364                   2             Wet or damp  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions  \
124812               Urban     Fine no high winds   
124822               Rural      Fine + high winds   
124823               Rural      Fine + high winds   
124827               Rural     Fine no high winds   
124862               Rural  Raining no high winds   
...                    ...                    ...   
628282               Rural     Fine no high winds   
628293               Rural  Raining no high winds   
628361               Rural     Fine no high winds   
628363               Rural            Fog or mist   
628364               Rural            Fog or mist   

                               Vehicle_Type  Year  Month  Day  DayOfWeek  
124812  Van / Goods 3.5 tonnes mgw or under  2019      1    1          1  
124822                                  Car  2019      1    2          2  
124823                                  Car  2019      1    2          2  
124827                                  Car  2019      1    2          2  
124862                                  Car  2019      1    5          5  
...                                     ...   ...    ...  ...        ...  
628282                                  Car  2021      2   11          3  
628293                Motorcycle over 500cc  2021      2   11          3  
628361                                  Car  2021      2   11          3  
62836

<h2>Insight#17
<h3>Theres 1288 that got into an accident in Test Valley

<h2>18.how many that got accident in District Area Portsmouth

In [32]:
ukacc[ukacc ['District Area'] == 'Portsmouth']

Index Accident_Severity Accident Date   Latitude  \
124813  2.01E+12            Slight    2019-01-01  50.802576   
124836  2.01E+12            Slight    2019-01-01  50.795573   
124840  2.01E+12            Slight    2019-01-03  50.820395   
124842  2.01E+12           Serious    2019-01-03  50.787647   
124855  2.01E+12            Slight    2019-01-04  50.853927   
...          ...               ...           ...        ...   
628362  2.01E+12           Serious    2021-02-11  50.847622   
628365  2.01E+12            Slight    2021-02-11  50.820320   
628366  2.01E+12            Slight    2021-02-11  50.795752   
628378  2.01E+12            Slight    2021-02-11  50.802843   
628385  2.01E+12           Serious    2022-03-06  50.843342   

             Light_Conditions District Area  Longitude  Number_of_Casualties  \
124813               Daylight    Portsmouth  -1.064068                     1   
124836  Darkness - lights lit    Portsmouth  -1.076695                     1   
124840               Daylight    Portsmouth  -1.076915                     1   
124842               Daylight    Portsmouth  -1.098131                     2   
124855               Daylight    Portsmouth  -1.053096                     1   
...                       ...           ...        ...                   ...   
628362               Daylight    Portsmouth  -1.074247                     2   
628365  Darkness - lights lit    Portsmouth  -1.067547                     3   
628366  Darkness - lights lit    Portsmouth  -1.076691                     1   
628378  Darkness - lights lit    Portsmouth  -1.086344                     1   
628385               Daylight    Portsmouth  -1.067514                     1   

        Number_of_Vehicles Road_Surface_Conditions           Road_Type  \
124813                   1             Wet or damp  Single carriageway   
124836                   2                     Dry          Roundabout   
124840                   2             Wet or damp  Single carriageway   
124842                   2             Wet or damp          Roundabout   
124855                   2                     Dry           Slip road   
...                    ...                     ...                 ...   
628362                   2             Wet or damp    Dual carriageway   
628365                   2             Wet or damp  Single carriageway   
628366                   3             Wet or damp          Roundabout   
628378                   2                     Dry  Single carriageway   
628385                   2                     Dry  Single carriageway   

       Urban_or_Rural_Area     Weather_Conditions Vehicle_Type  Year  Month  \
124813               Urban     Fine no high winds          Car  2019      1   
124836               Urban     Fine no high winds          Car  2019      1   
124840               Urban                  Other          Car  2019      1   
124842               Rural   Raining + high winds          Car  2019      1   
124855               Urban     Fine no high winds          Car  2019      1   
...                    ...                    ...          ...   ...    ...   
628362               Urban  Raining no high winds          Car  2021      2   
628365               Urban  Raining no high winds          Car  2021      2   
628366               Urban     Fine no high winds          Car  2021      2   
628378               Urban     Fine no high winds          Car  2021      2   
628385               Urban     Fine no high winds          Car  2022      3   

        Day  DayOfWeek  
124813    1          1  
124836    1          1  
124840    3          3  
124842    3          3  
124855    4          4  
...     ...        ...  
628362   11          3  
628365   11          3  
628366   11          3  
628378   11          3  
628385    6          6  

[2450 rows x 18 columns]

<h2>Insight#18
<h3>Theres 2450 that got into an accident in Portsmouth

<h1>Data Aggregation

<h2>1.How many Casualties there are in Broad Daylight in Accidents

In [33]:
Daylight = ukacc.groupby(['Light_Conditions','Number_of_Casualties']).count()

In [34]:
Daylight

Index  Accident_Severity  \
Light_Conditions            Number_of_Casualties                             
Darkness - lighting unknown 1                      5125               5125   
                            2                       956                956   
                            3                       251                251   
                            4                       104                104   
                            5                        31                 31   
...                                                 ...                ...   
Daylight                    42                        2                  2   
                            43                        1                  1   
                            45                        1                  1   
                            47                        1                  1   
                            62                        1                  1   

                                                  Accident Date  Latitude  \
Light_Conditions            Number_of_Casualties                            
Darkness - lighting unknown 1                              5125      5125   
                            2                               956       956   
                            3                               251       251   
                            4                               104       104   
                            5                                31        31   
...                                                         ...       ...   
Daylight                    42                                2         2   
                            43                                1         1   
                            45                                1         1   
                            47                                1         1   
                            62                                1         1   

                                                  District Area  Longitude  \
Light_Conditions            Number_of_Casualties                             
Darkness - lighting unknown 1                              5125       5125   
                            2                               956        956   
                            3                               251        251   
                            4                               104        104   
                            5                                31         31   
...                                                         ...        ...   
Daylight                    42                                2          2   
                            43                                1          1   
                            45                                1          1   
                            47                                1          1   
                            62                                1          1   

                                                  Number_of_Vehicles  \
Light_Conditions            Number_of_Casualties                       
Darkness - lighting unknown 1                                   5125   
                            2                                    956   
                            3                                    251   
                            4                                    104   
                            5                                     31   
...                                                              ...   
Daylight                    42                                     2   
                            43                                     1   
                            45                                     1   
                            47                                     1   
                            62                                     1   

                                                  Road_Surface_Conditions  \
Ligh

<h2>2.How many Casualties there are on different Vehicles 

In [35]:
Vehicle = ukacc.groupby(['Light_Conditions','Vehicle_Type']).count()

In [36]:
Vehicle

Index  \
Light_Conditions            Vehicle_Type                                  
Darkness - lighting unknown Agricultural vehicle                     19   
                            Bus or coach (17 or more pass seats)    267   
                            Car                                    4914   
                            Goods 7.5 tonnes mgw and over           185   
                            Goods over 3.5t. and under 7.5t          59   
...                                                                 ...   
Daylight                    Other vehicle                          4132   
                            Pedal cycle                             146   
                            Ridden horse                              3   
                            Taxi/Private hire car                  9752   
                            Van / Goods 3.5 tonnes mgw or under   24944   

                                                                  Accident_Severity  \
Light_Conditions            Vehicle_Type                                              
Darkness - lighting unknown Agricultural vehicle                                 19   
                            Bus or coach (17 or more pass seats)                267   
                            Car                                                4914   
                            Goods 7.5 tonnes mgw and over                       185   
                            Goods over 3.5t. and under 7.5t                      59   
...                                                                             ...   
Daylight                    Other vehicle                                      4132   
                            Pedal cycle                                         146   
                            Ridden horse                                          3   
                            Taxi/Private hire car                              9752   
                            Van / Goods 3.5 tonnes mgw or under               24944   

                                                                  Accident Date  \
Light_Conditions            Vehicle_Type                                          
Darkness - lighting unknown Agricultural vehicle                             19   
                            Bus or coach (17 or more pass seats)            267   
                            Car                                            4914   
                            Goods 7.5 tonnes mgw and over                   185   
                            Goods over 3.5t. and under 7.5t                  59   
...                                                                         ...   
Daylight                    Other vehicle                                  4132   
                            Pedal cycle                                     146   
                            Ridden horse                                      3   
                            Taxi/Private hire car                          9752   
                            Van / Goods 3.5 tonnes mgw or under           24944   

                                                                  Latitude  \
Light_Conditions            Vehicle_Type                                     
Darkness - lighting unknown Agricultural vehicle                        19   
                            Bus or coach (17 or more pass seats)       267   
                            Car                                       4914   
                            Goods 7.5 tonnes mgw and over              185   
                            Goods over 3.5t. and under 7.5t             59   
...                                                                    ...   
Daylight                    Other vehicle                             4132   
                            Pedal cycle                                146   
                            Ridden horse                                 3   
                    

<h2>19.Does a car have something to do with more accidents

In [37]:
f_oneway(ukacc[ukacc['Vehicle_Type'] == 'Car']['Number_of_Casualties'],ukacc[ukacc['Vehicle_Type'] == 'Taxi/Private hire car']['Number_of_Casualties'])

result, pvalue = f_oneway(ukacc[ukacc['Vehicle_Type'] == 'Car']['Number_of_Casualties'],ukacc[ukacc['Vehicle_Type'] == 'Taxi/Private hire car']['Number_of_Casualties'])

In [38]:
pvalue

np.float64(0.17617937353020258)

<h2>Insight#19
<h3>Its Influence Lacks Very much it has no relation

<h2>20.Does no Lighting in Complete Darkness Cause more Casualties?

In [39]:
f_oneway(ukacc[ukacc['Light_Conditions'] == 'Darkness-lights lit']['Number_of_Casualties'],ukacc[ukacc['Light_Conditions'] == 'Daylight']['Number_of_Casualties'])

result, pvalue = f_oneway(ukacc[ukacc['Light_Conditions'] == 'Darkness-lights lit']['Number_of_Casualties'],ukacc[ukacc['Light_Conditions'] == 'Daylight']['Number_of_Casualties'])

In [40]:
pvalue

np.float64(nan)

<h2>Insight#20
<h3>Its Influence Lacks Very much it has no relation

In [41]:
df_2020 = ukacc[ukacc['Year'] == 2020]

In [42]:
print(f'total number of accident in 2020 is {df_2020['Light_Conditions'].value_counts().sum()}')
df_2020['Light_Conditions'].value_counts()

total number of accident in 2020 is 70163


Light_Conditions
Daylight                       51605
Darkness - lights lit          13467
Darkness - no lighting          4085
Darkness - lighting unknown      717
Darkness - lights unlit          289
Name: count, dtype: int64

<h2>Insight#21
<h3>On 2020 the most dominating Conditions for Accidents was at Broad Daylight

<h2>Insight#22
<h3>The Lowest Accident rate was at Light conditions that are dimly lit

In [51]:
df_2021 = ukacc[ukacc['Year'] == 2021]

In [54]:
print(f'total number of accident in 2021 on Different Types of Transportation is {df_2021['Vehicle_Type'].value_counts().sum()}')
df_2021['Vehicle_Type'].value_counts()

total number of accident in 2021 on Different Types of Transportation is 461844


Vehicle_Type
Car                                      350121
Van / Goods 3.5 tonnes mgw or under       23741
Motorcycle over 500cc                     17713
Bus or coach (17 or more pass seats)      17291
Goods 7.5 tonnes mgw and over             11790
Motorcycle 125cc and under                10440
Taxi/Private hire car                      9074
Motorcycle over 125cc and up to 500cc      5387
Motorcycle 50cc and under                  5331
Goods over 3.5t. and under 7.5t            4196
Other vehicle                              3949
Minibus (8 - 16 passenger seats)           1351
Agricultural vehicle                       1329
Pedal cycle                                 125
Ridden horse                                  4
Data missing or out of range                  2
Name: count, dtype: int64

<h2>Insight#23
<h3>Cars have a Whopping 350121 accidents in total being the largest number than other vehicle types

<h2>Insight#24
<h3>other kind of vehicle types that are too different to be listed globally here are 3949 in Total

<h2>Insight#25
<h3>The Ridden Horse Being the lowest atleast at 4 Due to it being rare to be ridden other than other transportations